### ISSUE TITLE
Error when making SE

### ISSUE THREAD

**Issue by SophieS9** [arnesmits/DEP#4]
Hi Arne,

Not sure if this is an issue for here or for the the bioconductor forum, so let me know if I should re-post there. I'm trying to load some MaxQuant data into DEP following the instructions in the vignette. All going ok until I try to make the summarized experiment when I get the following error:

```
data_se<- make_se(data_unique, LFQ_columns, experimental_design)
Error: words is not a character vector
```

I've checked my input files and I can't see any formatting differences between them and the test data, apart from the fact that I'm using the full proteinGroups file.

Here is the input [proteinGroups](https://github.com/arnesmits/DEP/files/2668060/Maxwell_proteinGroups_v2.txt) file, the [experimental design](https://github.com/arnesmits/DEP/files/2668064/experimental_design.txt), and a [markdown](https://github.com/arnesmits/DEP/files/2668066/P202A_Analysis.pdf) with my code. 

Any ideas as to what's happening are welcome! 

Thanks!

Sophie

**Comment by arnesmits** [comment]
Dear Sophie,

Sorry for the delay in response. The problem is that the string-columns in your data frames are parsed into factors. This is easily circumvented. 

`data<-read.table("../AP17112_PBMC/Maxwell/Maxwell_proteinGroups_v2.txt", header=TRUE, sep="\t", stringsAsFactors = FALSE)
experimental_design<-read.table("../AP17112_PBMC/experimental_design.txt", header=TRUE, sep="\t", stringsAsFactors = FALSE)
`

After using this, all should work.

Best,
Arne
